package com.redmadrobot.debug.plugin.aboutapp.model

import android.content.Context
import com.redmadrobot.debug.core.DebugEvent
import com.redmadrobot.debug.plugin.aboutapp.AboutAppPlugin
import java.util.UUID

/**
 * Custom action button displayed in [AboutAppPlugin] under the application info section.
 *
 * Library consumers should use [Event]: clicks are published on the debug panel event bus as the provided [DebugEvent].
 *
 * [Direct] is intended for the library's own built-in actions that can be handled with application context only (e.g., copy a token, clear cache).
 * It is not part of the recommended public usage — prefer [Event] in application code.
 */
public sealed interface AboutAppAction {
    /**
     * Stable identifier used as a `LazyColumn` key. Auto-generated by default;
     * override only if you need a deterministic key (e.g., for UI tests).
     */
    public val id: String

    /** Button label. */
    public val title: String

    /**
     * Library-internal action whose [onClick] handler is invoked directly inside the plugin with the application context.
     * Reserved for built-in actions shipped with the library. Application code should use [Event] instead.
     */
    public class Direct(
        override val title: String,
        public val onClick: (Context) -> Unit,
        override val id: String = UUID.randomUUID().toString(),
    ) : AboutAppAction

    /**
     * Action that, when clicked, publishes [debugEvent] on the debug panel event bus.
     */
    public class Event(
        override val title: String,
        public val debugEvent: DebugEvent,
        override val id: String = UUID.randomUUID().toString(),
    ) : AboutAppAction
}
